# Generated by Django 5.2.7 on 2025-10-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='species',
            new_name='breed',
        ),
        migrations.AddField(
            model_name='pet',
            name='cat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='dog',
            field=models.BooleanField(default=False),
        ),
    ]
