# Generated by Django 5.2.7 on 2026-02-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_adoptionapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoptionapplication',
            options={'ordering': ['-applied_date'], 'verbose_name': 'Adoption Application', 'verbose_name_plural': 'Adoption Applications'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pet', 'verbose_name_plural': 'Pets'},
        ),
        migrations.RemoveField(
            model_name='pet',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='dog',
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='admin_comments',
            field=models.TextField(blank=True, verbose_name='Internal comments'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='decision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True, verbose_name='Follow-up date'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='follow_up_notes',
            field=models.TextField(blank=True, verbose_name='Follow-up notes'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='household_members',
            field=models.TextField(blank=True, help_text='Who lives in your home? (ages if children)', verbose_name='Household members'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='personal_reference',
            field=models.TextField(blank=True, help_text='Name and contact of a personal reference', verbose_name='Personal reference'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='vet_reference',
            field=models.TextField(blank=True, help_text='Name and contact of your veterinarian (if any)', verbose_name='Veterinary reference'),
        ),
        migrations.AddField(
            model_name='pet',
            name='additional_images',
            field=models.ImageField(blank=True, help_text='Additional photos (optional)', null=True, upload_to='pets/additional/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='intake_date',
            field=models.DateField(blank=True, help_text='Date when pet arrived at shelter', null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_cat',
            field=models.BooleanField(default=False, verbose_name='Is a Cat'),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_dog',
            field=models.BooleanField(default=False, verbose_name='Is a Dog'),
        ),
        migrations.AddField(
            model_name='pet',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='pets/main/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'Extra Large')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='special_needs',
            field=models.TextField(blank=True, help_text='Any special care requirements'),
        ),
        migrations.AddField(
            model_name='pet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccination_status',
            field=models.CharField(choices=[('up_to_date', 'Up to Date'), ('partial', 'Partial'), ('none', 'Not Vaccinated')], default='up_to_date', max_length=20),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='home_description',
            field=models.TextField(blank=True, help_text='Describe your home, yard, other pets, etc.', verbose_name='Home environment description'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Admin notes'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='previous_pet_experience',
            field=models.TextField(verbose_name='Previous experience with pets'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='reason_for_adoption',
            field=models.TextField(verbose_name='Why do you want to adopt this pet?'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
