# Generated by Django 5.2.7 on 2026-02-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0005_alter_pet_adopted_alter_pet_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
